"""create all tables

Revision ID: e41196798f3f
Revises:
Create Date: 2026-07-09 10:18:32.747296

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e41196798f3f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_id", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("released_at", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("stable_id LIKE 'tl.%%'", name=op.f("ck_patches_stable_id_format")),
        sa.CheckConstraint("version <> ''", name=op.f("ck_patches_version_not_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patches")),
    )
    op.create_index(op.f("ix_patches_stable_id"), "patches", ["stable_id"], unique=True)
    op.create_index(op.f("ix_patches_version"), "patches", ["version"], unique=True)
    op.create_table(
        "sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_id", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name=op.f("ck_sources_name_not_empty")),
        sa.CheckConstraint("stable_id LIKE 'tl.%%'", name=op.f("ck_sources_stable_id_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_index(op.f("ix_sources_name"), "sources", ["name"], unique=False)
    op.create_index(op.f("ix_sources_stable_id"), "sources", ["stable_id"], unique=True)
    op.create_table(
        "entities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stable_id", sa.String(length=200), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("semantic_version", sa.String(length=50), nullable=False),
        sa.Column("patch_version", sa.String(length=50), nullable=False),
        sa.Column("is_validated", sa.Boolean(), nullable=False),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=1024).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("source_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("patch_version <> ''", name=op.f("ck_entities_patch_version_not_empty")),
        sa.CheckConstraint(
            "semantic_version <> ''", name=op.f("ck_entities_semantic_version_not_empty")
        ),
        sa.CheckConstraint("stable_id LIKE 'tl.%%'", name=op.f("ck_entities_stable_id_format")),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_entities_source_id_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entities")),
    )
    op.create_index(op.f("ix_entities_entity_type"), "entities", ["entity_type"], unique=False)
    op.create_index(op.f("ix_entities_is_validated"), "entities", ["is_validated"], unique=False)
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    op.create_index(op.f("ix_entities_patch_version"), "entities", ["patch_version"], unique=False)
    op.create_index(op.f("ix_entities_stable_id"), "entities", ["stable_id"], unique=True)
    op.create_index(
        "ix_entities_type_validated", "entities", ["entity_type", "is_validated"], unique=False
    )
    op.create_table(
        "buffs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_buffs_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buffs")),
    )
    op.create_table(
        "formulas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_formulas_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_formulas")),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_items_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
    )
    op.create_table(
        "monsters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_monsters_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monsters")),
    )
    op.create_table(
        "npcs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_npcs_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_npcs")),
    )
    op.create_table(
        "set_bonuses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_set_bonuses_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_set_bonuses")),
    )
    op.create_table(
        "skill_cores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_skill_cores_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_cores")),
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_skills_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
    )
    op.create_table(
        "stats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_stats_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stats")),
    )
    op.create_table(
        "traits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["entities.id"], name=op.f("fk_traits_id_entities"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traits")),
    )
    op.create_table(
        "accessories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["items.id"], name=op.f("fk_accessories_id_items"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_accessories")),
    )
    op.create_table(
        "armor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["items.id"], name=op.f("fk_armor_id_items"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_armor")),
    )
    op.create_table(
        "bosses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["monsters.id"], name=op.f("fk_bosses_id_monsters"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bosses")),
    )
    op.create_table(
        "buff_stats",
        sa.Column("buff_id", sa.Uuid(), nullable=False),
        sa.Column("stat_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buff_id"], ["buffs.id"], name=op.f("fk_buff_stats_buff_id_buffs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["stat_id"], ["stats.id"], name=op.f("fk_buff_stats_stat_id_stats"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("buff_id", "stat_id", name=op.f("pk_buff_stats")),
    )
    op.create_table(
        "formula_inputs",
        sa.Column("formula_id", sa.Uuid(), nullable=False),
        sa.Column("stat_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["formula_id"],
            ["formulas.id"],
            name=op.f("fk_formula_inputs_formula_id_formulas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stat_id"],
            ["stats.id"],
            name=op.f("fk_formula_inputs_stat_id_stats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("formula_id", "stat_id", name=op.f("pk_formula_inputs")),
    )
    op.create_table(
        "formula_outputs",
        sa.Column("formula_id", sa.Uuid(), nullable=False),
        sa.Column("stat_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["formula_id"],
            ["formulas.id"],
            name=op.f("fk_formula_outputs_formula_id_formulas"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stat_id"],
            ["stats.id"],
            name=op.f("fk_formula_outputs_stat_id_stats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("formula_id", "stat_id", name=op.f("pk_formula_outputs")),
    )
    op.create_table(
        "item_traits",
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("trait_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_traits_item_id_items"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trait_id"],
            ["traits.id"],
            name=op.f("fk_item_traits_trait_id_traits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("item_id", "trait_id", name=op.f("pk_item_traits")),
    )
    op.create_table(
        "monster_skills",
        sa.Column("monster_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monster_id"],
            ["monsters.id"],
            name=op.f("fk_monster_skills_monster_id_monsters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_monster_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("monster_id", "skill_id", name=op.f("pk_monster_skills")),
    )
    op.create_table(
        "set_bonus_items",
        sa.Column("set_bonus_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_set_bonus_items_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["set_bonus_id"],
            ["set_bonuses.id"],
            name=op.f("fk_set_bonus_items_set_bonus_id_set_bonuses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("set_bonus_id", "item_id", name=op.f("pk_set_bonus_items")),
    )
    op.create_table(
        "skill_buffs",
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column("buff_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["buff_id"], ["buffs.id"], name=op.f("fk_skill_buffs_buff_id_buffs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_buffs_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("skill_id", "buff_id", name=op.f("pk_skill_buffs")),
    )
    op.create_table(
        "skill_core_skills",
        sa.Column("skill_core_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_core_id"],
            ["skill_cores.id"],
            name=op.f("fk_skill_core_skills_skill_core_id_skill_cores"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_core_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("skill_core_id", "skill_id", name=op.f("pk_skill_core_skills")),
    )
    op.create_table(
        "trait_stats",
        sa.Column("trait_id", sa.Uuid(), nullable=False),
        sa.Column("stat_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stat_id"], ["stats.id"], name=op.f("fk_trait_stats_stat_id_stats"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trait_id"],
            ["traits.id"],
            name=op.f("fk_trait_stats_trait_id_traits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("trait_id", "stat_id", name=op.f("pk_trait_stats")),
    )
    op.create_table(
        "weapons",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"], ["items.id"], name=op.f("fk_weapons_id_items"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_weapons")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weapons")
    op.drop_table("trait_stats")
    op.drop_table("skill_core_skills")
    op.drop_table("skill_buffs")
    op.drop_table("set_bonus_items")
    op.drop_table("monster_skills")
    op.drop_table("item_traits")
    op.drop_table("formula_outputs")
    op.drop_table("formula_inputs")
    op.drop_table("buff_stats")
    op.drop_table("bosses")
    op.drop_table("armor")
    op.drop_table("accessories")
    op.drop_table("traits")
    op.drop_table("stats")
    op.drop_table("skills")
    op.drop_table("skill_cores")
    op.drop_table("set_bonuses")
    op.drop_table("npcs")
    op.drop_table("monsters")
    op.drop_table("items")
    op.drop_table("formulas")
    op.drop_table("buffs")
    op.drop_index("ix_entities_type_validated", table_name="entities")
    op.drop_index(op.f("ix_entities_stable_id"), table_name="entities")
    op.drop_index(op.f("ix_entities_patch_version"), table_name="entities")
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_index(op.f("ix_entities_is_validated"), table_name="entities")
    op.drop_index(op.f("ix_entities_entity_type"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_sources_stable_id"), table_name="sources")
    op.drop_index(op.f("ix_sources_name"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_patches_version"), table_name="patches")
    op.drop_index(op.f("ix_patches_stable_id"), table_name="patches")
    op.drop_table("patches")
    # ### end Alembic commands ###
